### ISSUE TITLE
[Task 1]Tagging cloud resources. 

### ISSUE THREAD

**Issue by kravetsd** [schweppes2205/terraform_tasks#1]
As task1 says 
`All cloud resources should have tags Date_creation, OS_type, Your_First_Name, Your_Last_Name, AWS_Account_ID.`

https://github.com/schweppes2205/terraform_tasks/blob/b775c6d353494861d8ecd1b9d49e605f06281439/task_1/module/main.tf#L17-L20

**Comment by schweppes2205** [comment]
Tags are added to key_pair for both tasks.
