### ISSUE TITLE
[Improvement] Please make possible to deploy your VMs to the particular VPC.

### ISSUE THREAD

**Issue by kravetsd** [schweppes2205/terraform_tasks#4]
As for now I can see that you deploy your setup to a default VPC. Let's make possible to deploy your setup to some VPC. Also please note that the target VPC can have several subnets in each availability zone and this case also has to be handled somehow.

**Comment by schweppes2205** [comment]
done with the last commit.

**Comment by schweppes2205** [comment]
add subnets

**Comment by schweppes2205** [comment]
a new filter has bee added:
```terraform
data "aws_subnet" "subnet" {
  vpc_id            = data.aws_vpc.vpc.id
  availability_zone = var.availability_zone
  filter {
    name   = "tag:Name"
    values = [var.subnet_name]
  }
}
```
