### ISSUE TITLE
[Task 2] How much resources you create in case of count is equal to `0`?

### ISSUE THREAD

**Issue by kravetsd** [schweppes2205/terraform_tasks#5]
https://github.com/schweppes2205/terraform_tasks/blob/b775c6d353494861d8ecd1b9d49e605f06281439/task_2/module/main.tf#L23

It is a bit tricky but if I set count to 0 in your module then it still creates cloud resources.
Please take a look and test that case.

**Comment by schweppes2205** [comment]
in case input variable of count is 0 the only resource that is created by the module is ssh key pair, no cloud resource is created.

**Comment by schweppes2205** [comment]
set condition for key-pair

**Comment by schweppes2205** [comment]
a new filter has bee added:
data "aws_subnet" "subnet" {
  vpc_id            = data.aws_vpc.vpc.id
  availability_zone = var.availability_zone
  filter {
    name   = "tag:Name"
    values = [var.subnet_name]
  }
}

**Comment by schweppes2205** [comment]
a new conditional count was added to key-pair resource. If ec2 count is more than 0, then create a key-pair.
```terraform
resource "aws_key_pair" "ssh_key" {
  count      = var.instance_count > 0 ? 1 : 0
  key_name   = var.ssh_public_key.name
  public_key = var.ssh_public_key.value
  tags = merge(var.tags, {
    AWS_Account_ID = data.aws_caller_identity.current.account_id
  })
}
```
In case the key-pair created, the first one with index 0 will be used for each ec2 instance
```terraform
resource "aws_instance" "instance" {
  key_name = aws_key_pair.ssh_key[0].key_name
...
```
