### ISSUE TITLE
[Improvement] What if we try to make this a bit universal.

### ISSUE THREAD

**Issue by kravetsd** [schweppes2205/terraform_tasks#6]
https://github.com/schweppes2205/terraform_tasks/blob/b775c6d353494861d8ecd1b9d49e605f06281439/task_1/module/main.tf#L5

Let's try to remove hardcode from here. 
Please suggest a solution to make the VM setup more universal and make it work for other OS types. (centos. ubuntu)

**Comment by schweppes2205** [comment]
changed in the last commit.

**Comment by schweppes2205** [comment]
add separate users for different ami
